#!/bin/bash

g++ atkin.cpp -l OpenCL || exit 1

read -a range -p "Podaj koniec n zakresu 1 do n który ma zostać przesitowany: " 
while [ "$range" -lt "6" ]
do
	read -a range -p "Podaj n większe od 5: "
done

time echo $range | ./a.out 
rm a.out
